# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUyT0fVb9oGSSkvqvGfjQ24guLQqLi1b
"""

import pandas as pd
baza={
    "FISH":["Foziljonova Mexriniso","Poziljonov Asomiddin","Poziljonova Xalimaxon","Poziljonova Oishabegim","Foziljonov Zuhriddin","Poziljonova Ominaxon","Poziljonov Ziyovuddin","Foziljonov Abdushkur","Abdurasulova Sarvinoz","Oribjonova Mubinaxon" ],
    "Yoshi":["19" ,"9","17","13","19","18","14","24" ,"19","18"],
    'Manzili':["Farg'ona shahar", "Sultonobod shaharcha","Sultonobod shaharcha","Andijon shahar","Qurama ko'chasi","Qurama ko'chasi","Suv boshi","Toshkent shahar","ulug'nor tumani","Farg'ona shahar" ],
    "Jinsi": ["ayol ","erkak","ayol ","ayol ","erkak","ayol ","erkak","erkak","ayol ","ayol " ],
    "Maktabi":["TATUFF" ,"35-maktab","ADU","35-maktab","ADU","ADU","35-maktab","ChDPI","TATUFF","TATUFF"]
    }
db=pd.DataFrame(baza)
print(db)

filtr=db[(db["Jinsi"]=="ayol ") & (db["Maktabi"]=="TATUFF")]
print(filtr)

filtr=db[(db["Jinsi"]=="ayol ") & (db["Maktabi"]=="TATUFF") & (db["Yoshi"]>"18") ]
print(filtr)